_welcome:
    pattern:  /
    defaults: { _controller: BananasUiBundle:Default:index }
_assetic:
    resource: .
    type:     assetic

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt
_main:
    resource: routing.yml
